import { TabState } from '../types';

export function exportAuditGuardScope(
  state: TabState,
  overrideExclusions?: string[],
  overrideInScope?: string[]
): string {
  let hostname = 'unknown_host';
  let origin = '';
  try {
    const parsed = new URL(state.url);
    hostname = parsed.hostname.replace(/\./g, '_');
    origin = parsed.origin;
  } catch {}

  const routes = state.routes || [];
  const discoveredPaths = routes.map(r => r.path);
  const adminPaths = routes.filter(r => r.type === 'admin').map(r => r.path);

  // Combine in-scope targets
  const inScope = new Set<string>();
  if (overrideInScope && overrideInScope.length > 0) {
    for (const s of overrideInScope) inScope.add(s);
  } else if (state.customInScope && state.customInScope.length > 0) {
    for (const s of state.customInScope) inScope.add(s);
  } else if (origin) {
    inScope.add(origin);
  }

  // Combine exclusions: baseline + custom configured exclusions
  const exclusions = new Set<string>(['/logout', '/delete', '/billing']);

  if (overrideExclusions && overrideExclusions.length > 0) {
    for (const p of overrideExclusions) exclusions.add(p);
  } else if (state.customExclusions && state.customExclusions.length > 0) {
    for (const p of state.customExclusions) exclusions.add(p);
  }

  let yaml = `# AuditGuard Scope Definition generated by StateHunter\n`;
  yaml += `# Target: ${state.url || 'N/A'}\n`;
  yaml += `# Generated: ${new Date().toISOString()}\n`;

  // Inject RFC 9116 security.txt metadata if available
  const sec = state.wellKnown?.securityTxt;
  if (sec) {
    yaml += `#\n# --- Vulnerability Disclosure Policy (RFC 9116) ---\n`;
    if (sec.policyUrl) yaml += `# Policy URL: ${sec.policyUrl}\n`;
    if (sec.contacts.length > 0) yaml += `# Contact: ${sec.contacts.join(', ')}\n`;
    if (sec.acknowledgmentsUrl) yaml += `# Acknowledgments: ${sec.acknowledgmentsUrl}\n`;
    if (sec.canonical) yaml += `# Canonical: ${sec.canonical}\n`;
  }

  yaml += `\nprograms:\n`;
  yaml += `  ${hostname}:\n`;
  yaml += `    name: "${state.title || hostname}"\n`;
  yaml += `    in_scope:\n`;
  for (const s of Array.from(inScope)) {
    yaml += `      - "${s}"\n`;
  }

  // Write merged excluded_paths
  yaml += `    excluded_paths:\n`;
  for (const exp of Array.from(exclusions)) {
    yaml += `      - "${exp}"\n`;
  }

  // Discovered SPA endpoints
  yaml += `    discovered_endpoints:\n`;
  for (const p of discoveredPaths.slice(0, 100)) {
    yaml += `      - "${p}"\n`;
  }

  if (adminPaths.length > 0) {
    yaml += `    flagged_sensitive_endpoints:\n`;
    for (const a of adminPaths) {
      yaml += `      - "${a}"\n`;
    }
  }

  // Robots.txt Disallow directives section
  if (state.wellKnown?.robotsDisallow && state.wellKnown.robotsDisallow.length > 0) {
    yaml += `    robots_disallow_directives:\n`;
    for (const rob of state.wellKnown.robotsDisallow.slice(0, 50)) {
      yaml += `      - "${rob}"\n`;
    }
  }

  return yaml;
}
